### ISSUE TITLE
Add keyboard type option

### ISSUE THREAD

**Issue by r-kgy** [fayeed/dash_chat#102]
I would like to add the options for customizing the keyboard type ( keyboardAppearance, keyboardType, etc.).
If you don't have a problem about this issue, I'll put out a PR, but do you have any concerns about this?

**Comment by fayeed** [comment]
I don't see the point of adding `keyboardType` property since this package is for chat, can you explain your use case?

**Comment by SebastienBtr** [comment]
Closing this for now because the author didn't respond

**Comment by timorss** [comment]
Any news?
In case of a chat bot, there are a few questions with different answers,
What is your email, age, phone number, etc..
So for age for example we need a keyboard of type number.
