### ISSUE TITLE
User avatar from url with bearer token authorization

### ISSUE THREAD

**Issue by mateus96mt** [fayeed/dash_chat#103]
I work in a application where the avatars of the users (chat users) comes from an endpoint where a bearer token authorization is needed and looking into dash_chat code there is only a string for user avatar url and i cannot pass the bearer token so the avatar don't load.

Change the avatar of chat from url string to an image would help, or allowing a way to pass bearer token and not just the avatar url.

If there is a way to pass bearer token authorization to pick user avatar i would appreciate a explanation of how to do it.

**Comment by fayeed** [comment]
This is a very specific use case so won't be implemented in the package but you easily implement this using `avatarBuilder` take a look at the documentation for more explanation.

**Comment by mateus96mt** [comment]
The `avatarBuilder` changes the avatar for all users in chat? The avatarBuilder receives only one ChatUser and uses the widget returned as default avatar widget for all user. At least this was the behavior i have observed.

Is there a way to set custom avatar for each User?
