### ISSUE TITLE
How to add a custom avatar in the chat

### ISSUE THREAD

**Issue by dulajdanu** [fayeed/dash_chat#109]
How to add a custom avatar for the chat.i cant understand how to use the avatarbuilder

**Comment by elgansayer** [comment]
Use avatarBuilder.

`      avatarBuilder: (dash.ChatUser chatUser) {
        var foundUser = chatGroup.userAccounts
            .firstWhere((ua) => ua.id == chatUser.uid, orElse: () => null);

        if (foundUser == null) {
          return UserAccount.defaults().getAvatar(context, button: false);
        }

        return foundUser.getAvatar(context);
      },`
