### ISSUE TITLE
This is not a bug, I just do not understand how to replace the default sendButtonBuilder 

### ISSUE THREAD

**Issue by SushiRoll53** [fayeed/dash_chat#11]
I was using the example and everything is working flawlessly, but then I try to change the default icon send but it ask for a specific time and I am not sure on how to create a type Widget Function(Function)
Could someone illustrate me. I do not need to modify the functionality, just the icon colors.

**Comment by PolymathWhiz** [comment]
One way i'll suggest is to change it from the core code to fit what you want

**Comment by fayeed** [comment]
@SushiRoll53 Its really simple you create a function that returns a widget and the function you see a parameter is actually the `onSend` function you passed to the Dashchat.

Here's an example:
```dart
Function sendButtonBuilder(Function onSend) {
  return IconButton(
     icon: Icon(
       Icons.send,
       color: Colors.white  
     ),
     onPress: onSend
  );
}

// Your dashchat code
Dashchat(
  sendButtonBuilder: sendButtonBuilder(),
)
```

**Comment by PolymathWhiz** [comment]
> @SushiRoll53 Its really simple you create a function that returns a widget and the function you see a parameter is actually the `onSend` function you passed to the Dashchat.
> 
> Here's an example:
> 
> ```dart
> Function sendButtonBuilder(Function onSend) {
>   return IconButton(
>      icon: Icon(
>        Icons.send,
>        color: Colors.white  
>      ),
>      onPress: onSend
>   );
> }
> 
> // Your dashchat code
> Dashchat(
>   sendButtonBuilder: sendButtonBuilder(),
> )
> ```

Much better

**Comment by SushiRoll53** [comment]
Cool it seems easy, I tried as the following, I had to make some modifications so I was able to run a test
```
sendButtonBuilder(Function onSend) {
  return IconButton(
     icon: Icon(
       Icons.send,
       color: Colors.white  
     ),
     onPress: onSend
  );
}

Dashchat(
  sendButtonBuilder: sendButtonBuilder(onSend),
)
```
and the icon does not get replace it.
Do you have another way I can try to solve this?

**Comment by SushiRoll53** [comment]
It's me again, for the record I managed to solve with some help, here it is how I could fix it
``` dart
sendButtonBuilder(Function onSend) {
  return IconButton(
     icon: Icon(
       Icons.send,
       color: Colors.white  
     ),
     onPressed: onSend
  );
}

Dashchat(
  sendButtonBuilder: (function) {
    sendButtonBuilder(function)
  },
)
```
I'm gonna close it, thank you for your responses.

**Comment by kornha** [comment]
Reopening. This does not work, the onSend method does not get triggered. As this is not expected behavior, this is a bug.
