### ISSUE TITLE
new issue on 1.1.12 -> you must set inputDisabled flag or get null error

### ISSUE THREAD

**Issue by m-j-g** [fayeed/dash_chat#111]
starting in 1.1.12:

Create DashChat() object and don't add the 'inputDisabled' flag - get null error.  Easy fix just adding the flag, but it looks like this is supposed to default to false if its omitted.

**Comment by fayeed** [comment]
@m-j-g Thanks for reporting the issue I will take a look and deploy a quick fix for this

**Comment by fayeed** [comment]
@m-j-g Updated the package to `1.1.13`.
