### ISSUE TITLE
onSend function not being called when onTextChange function is passed

### ISSUE THREAD

**Issue by javaCoincidence** [fayeed/dash_chat#114]
**Describe the bug**
when you have both onTextChange and onSend parameters passed, the onSend function is not being called and the send button is inActive!

**Expected behavior**
the onSend function should be called as expected despite having onTextChange function passed

**Desktop (please complete the following information):**
 flutter for web,  dash_chat: ^1.1.13

**Comment by fayeed** [comment]
@javaCoincidence Are you using this library on Flutter web? If you are the library does not support this  Flutter for the web yet.

**Comment by javaCoincidence** [comment]
I see, thanks!
