### ISSUE TITLE
[v2] Dashchat v2 spec discussion

### ISSUE THREAD

**Issue by fayeed** [fayeed/dash_chat#127]
# Dashchat v2.0

**Note**: This document is just for discussion purposes only, nothing has been finalized yet, if you have any suggestions that could help in improving the package feel free to let us know. 

If you want to help with development do reach out to me or @SebastienBtr (you can find details on our Github profile)

## Goals
1. Change the API to make it more modular (See below the new API)
2. Video support.
3. Audio support.
4. Gif support.
5. **Multiple media support**: Right now ChatMessage only has 2 properties: image & video instead we can have a new property media: `List<ChatMedia>` which will take care of handling all the media content associated with the message.
show embedded URLs: In all modern chat applications when a URL is embedded the right representation is given that is what a user can expect from the website if they visit. The information relayed is the title, description & banner image in most cases. This can be easily achieved using `open_graph_parser`.
6. Better default design.
7. **Using `flutter_hooks` to make code more readable**: I am a big-time react_hooks user & when the flutter_hooks were introduced by Remi I immediately jumped to using it. I love them. The basic idea for using hooks for this package is that it will help abstract the code from widgets into more manageable functions, also at the same time making it easy for maintainers to easily debug or add more functions.
8. **Tests**: Initially when I learned Flutter I just looked over tests as not needed as I was the only one maintaining & adding functionality to the package. As the package grew & more people started contributing to the project it has made people difficult to test each functionality after a PR manually which in most cases causes an error, so now that we are working on v2 we add more tests to help with maintaining the package easier.
9. More option/ granular customization.
10. Reply to message support.
11. @ Mentions functionality.
12. Composer actions (to attach photos, etc.)
13. A new property to indicate someone is typing.
14. New property for ChatMessage - sent, received & pending.
15. Placeholder image for avatars.
16. **Better documentation**: As most of you might know the current documentation is really confusing, So I would also like to have better documentation, maybe a separate docs site built using Docusaurus with examples.
17. Add multiple examples with different databases. 
18. Use nanoid instead of UUID.
 
## Change the API to make it more modular.

**What is the need for changing the API?**
Right now DashChat is just a very huge single widget, which creates problems for new users to figure out all the functionality the widget provides. At the same time, any new property added must also be added to all the widgets down the tree with proper assertions for null safe type check which is a huge problem because it introduces new bugs in the code.

**Note**: The API mentioned below is not final & will most likely change.

```dart
Dashchat({
  @required ChatUser currentUser, 
  @required Function(ChatMessage) onSend,
  @required List<ChatMessage> messages,
  Key key,
  InputOptions inputOptions = InputOptions(),
  MessageOptions messageOptions = MessageOptions(),
  MessageListOptions messageListOptions = MessageListOptions(),
  QuickReplyOptions quickReplyOptions = QuickReplyOptions(),
  ScrollToBottomOptions scrollToBottomOptions = ScrollToBottomOptions(),
  bool readoOnly = false,
  DashchatStyle dashchatStyle,
  String Function() messageIdGenerator,
  List<ChatUser> typingUsers,
  // List<ChatUser> participants,  
  // could have a different field called participants with all the list of the users 
  // rather then having all user info in each message, 
  // might need to add a new property to the [ChatUser] called `currentUser: bool`
});
```

```dart
DashchatStyle({
  double height,
  double width,
  EdgeInsets padding,
  EdgeInsets margin,
  Image backgroundImage,
  Color backgroundColor,
});
```

```dart
InputOptions({
  TextEditingController textController = TextEditingController(),
  FocusNode focusNode = FocusNode(),
  TextDirection inputTextDirection = TextDirection.ltr,
  String hintText = 'Write a message...'
  TextStyle hintStyle,
  ChatUser Function(String) onMention,
  Function(String) onTextChange,
  bool inputDisabled = false,
  InputDecoration inputDecoration,
  TextCapitalization textCapitalization = TextCapitalization.none,
  bool alwaysShowSend = false,
  bool sendOnEnter = false, // Might not be needed because of textInputAction
  TextInputAction textInputAction,
  double maxInputLength,
  List<Widget> leading,
  List<Widget> trailing,
  Widget Function(Function) sendButtonBuilder,
  TextStyle inputTextStyle,
  BoxDecoration inputContainerStyle,
  int inputMaxLines = 5,
  InputDecoration inputDecoration,
  Widget Function() inputFooterBuilder,
  bool showTraillingBeforeSend = false,
  EdgeInsets inputToolbarPadding,
  EdgeInsets inputToolbarMargin,
  Widget Function(Function) sendButtonBuilder,
  CursorStyle cursorStyle,
});
```
```dart
CursorStyle({
  Color color,
  bool hide,
  double width = 2.0,
});
```

```dart
MessageListOptions({
  DateFormat dateSeparatorFormat = DateFormat('dd MMM yyyy'),
  Widget Function(String) dateSeparatorBuilder,
  SeparatorFrequency separatorFrequency = SeparatorFrequency.days,
  bool showAvatarForEveryMessage = false,
  ScrollController scrollController,
  Widget Function() chatFooterBuilder,
  bool showFooterBeforeQuickReplies = false,
  bool shouldStartMessagesFromTop = false,
  bool shouldShowLoadEarlier = true,
  Widget Function() showLoadEarlierBuilder,
  Function onLoadEarlier,
});
```

```dart
MessageOptions({
  messageContainerFlex: 1,
  DateFormat timeFormat = DateFormat('HH:mm'),
  bool showTime = true,
  bool showCurrentUserAvatar = false,
  bool showOtherUsersAvatar = true,
  double avatarMaxSize = 30.0,
  Widget Function(ChatUser) avatarBuilder,
  Function(ChatUser) onPressAvatar,
  Function(ChatUser) onLongPressAvatar,
  Function(ChatMessage) onLongPressMessage,
  Color currentUserContainerColor, // Default to primary theme
  Color currentUserTextColor, // Default using theme
  Color containerColor = Colors.grey[100],
  Color textColor = Colors.black,
  Widget Function(ChatMessage, [ChatMessage,  ChatMessage]) messageBuilder, // currentMessage, [previousMessage, nextMessage]
  Widget Function(String, [ChatMessage] messageTextBuilder,
  Widget Function(String, [ChatMessage]) messageImageBuilder,
  Widget Function(String, [ChatMessage]) messageTimeBuilder,
  List<MatchText> parsePatterns // By default ParsedType.URL is defined using launchUrl,
  BoxDecoration messageContainerDecoration,
  EdgeInsets messageContainerPadding,
  List<Widget> Function(ChatMessage) messageButtonsBuilder,
  EdgeInsets messagePadding,
  bool textBeforeImage = true,
  BoxDecoration Function(ChatMessage, bool) messageDecorationBuilder,
  Widget Function(ChatMessage) top,
  Widget Function(ChatMessage) bottom,
});
```

```dart
QuickReplyOptions({
  Function(Reply) onQuickReply,
  EdgeInsets quickReplyPadding,
  BoxDecoration quickReplyStyle,
  TextStyle quickReplyTextStyle,
  Widget Function(Reply) quickReplyBuilder,
  bool quickReplyScroll = false,
});
```

```dart
ScrollToBottomOptions({
  bool disabled = false,
  Widget Function() scrollToBottomBuilder,
  Function onScrollToBottomPress,
  ScrollToBottomStyle scrollToBottomStyle,
});
```

```dart
ScrollToBottomStyle({
  Color backgroundColor,
  Color textColor,
  double bottom = 70.0,
  double left = 0.0,
  double right: 20.0,
  double top = 0.0,
  double height = 45.0,
  double width = 45.0,
  IconData icon,
});
```

```dart
ChatMessage({
  @required String text,
  @required ChatUser user,
  String id,
  List<ChatMedia> medias,
  List<QuickReply> quickReplies,
  bool keepQuickReplies = false,
  Map<String, dynamic> customProperties,
  DateTime createdAt,
  List<Widget> buttons,
  List<ChatUser> mentions,
  MessageStatus status = MessageStatus.none // read, received, pending
  List<ChatMessage> replies,
});
```

```dart
QuickReply({
  @required String title,
  String value, // Use title by default
  String messageId,
});
```

```dart
ChatMedia({
  @required String src,
  @required String mimeType, // "image | video | audio | other"
  Widget Function(src) builder,
  DateTime uploadedDate,
});
```

```dart
ChatUser({
  String id,
  String profileImage,
  Map<String, dynamic> customProperties,
  String name, // Either name of firstName must be provided  
  String firstName,
  String lastName,
});
```

**Comment by SebastienBtr** [comment]
Maybe put this in a file so we can commit/PR change

**Comment by aytunch** [comment]
Will v2 have its separate repo? And did you consider bloc/cubit for v2? It is very suitable state management solution for chat app.

**Comment by fayeed** [comment]
@aytunch we will just create a separate branch for v2, as for state management solution we won't use any because I don't want to limit the package to anyone solution, though I was thinking of Adapter based approach where we could have adapters for different state management solutions to support it, we will see how it goes.

**Comment by ryanhz** [comment]
Hi, can you add bubble to the message box using this https://pub.dev/packages/bubble ?

**Comment by fayeed** [comment]
@ryanhz I don't think we will add this because I want to keep as few dependencies as possible, but we will make the builders a little easier so implementing by yourself would be easier.

**Comment by ryanhz** [comment]
I know your package is already fantastic.  Or we can add option to have the bubble nip or not, using the same way as bubble?  The bubble package is very simple compare to your package.

**Comment by SebastienBtr** [comment]
@ryanhz Using Bubble internally wont really change anything, the package will provide a default design and if you want to override the dashchat message design you simply use the provided builder where you can of course use Bubble if you want

**Comment by invipal** [comment]
I think, audio call and video call features with WebRTC will be nice .

**Comment by fayeed** [comment]
@invipal I don't think we will add this as the goal of the package to provide a chat view, all this functionality will be left to users to implement. Thanks for the suggestions.

**Comment by fluttercid** [comment]
Hi Fayeed,
I really thank you for your package.
I need to add a sentence case in user input box.
When will you release dash-chat v2?
Thank you.

P.S: Can I hide avatars both user and other users?

**Comment by alfredjingle** [comment]
Thanks for the baller package. :+1: :champagne: 

Tiny thing, and don't know if it will be applicable in v2, but if there are any hard-coded phrases like 'Copy to clipboard' can internationalisation be set up, so that the phrase can be change for non English language apps.

Thank you!

**Comment by fayeed** [comment]
@fluttercid we haven't started working on it yet, but when we do it shouldn't take us more than 2 weeks. Also, you can hide user avatar only, if you want to this right now, you can use `avatarBuilder` and just return an empty `Container`.

**Comment by fayeed** [comment]
@alfredjingle, we haven't looked at internationalization support, I think you are referring to the `onLongTap` on message which shows a bottom sheet, you can just override the method to call your custom modal.

**Comment by alfredjingle** [comment]
One more small suggestion: would it be possible to have the ability to add a marker in the list of messages which shows from which point there are unread messages?

I guess it would currently be possible with a custom message builder, but wondering if it would be worth adding a specific property for it.

**Comment by fayeed** [comment]
@alfredjingle That's a good suggestion, I will most likely add this.

**Comment by aytunch** [comment]
@fayeed is there support for unread message count on chats list screen? Also something like whatsapp's archived feature?

**Comment by SebastienBtr** [comment]
@aytunch We can provide a variable that count the number of ChatMessage passed that don't have the status set to `read`.
Can you explain "whatsApp archived feature"? keep in mind that Dashchat is only providing the UI

**Comment by aytunch** [comment]
@SebastienBtr What I mean by archived feature of whatsapp is when you are on the chat list screen you see the list of people you have chatted with recently at the top. If you scroll up(like a pull to refresh), you see the archived chats appear on top of the list if you have any. This is not as important as the unread message count but I wanted to throw it before v2 specs are set anyways

**Comment by fayeed** [comment]
@aytunch This can easily be implemented by just counting the number of unread messages on your side, as you know there is a `status` property with every message which you can use to count, as @SebastienBtr mentioned we could provide a variable for Dashchat. 

As for the archived message you can just use the `customProperties` property to indicate which message has been archived. I don't think we will implement this feature though.

**Comment by SebastienBtr** [comment]
Yeah it doesn't seem like something we will implement, this package is for the UI of the chat room not the chat list.

**Comment by irfanbacker** [comment]
Adding support for system messages would be good. Something like a centered bubble similar to the date which can be used for situations like user joins and leavings.

**Comment by irfanbacker** [comment]
Adding support for system messages would be good. Something like a centered bubble similar to the date which can be used for situations like user joins and leavings or major events in the chat.

**Comment by themadmrj** [comment]
When talking about a chat library, I think a good reference is this Android package : 
[](https://github.com/stfalcon-studio/ChatKit)
All important functionnalities are there and easily customizable. I built a chat with audio, video, image, text, richtext, typing indicator, chat room, avatar+group avatar, message ordering & room ordering, new message badges with counter... Looking to do the same in Flutter now

**Comment by aytunch** [comment]
> When talking about a chat library, I think a good reference is this Android package :
> 
> All important functionnalities are there and easily customizable. I built a chat with audio, video, image, text, richtext, typing indicator, chat room, avatar+group avatar, message ordering & room ordering, new message badges with counter... Looking to do the same in Flutter now

@themadmrj just making sure if you forgot to add the link to a package?

**Comment by themadmrj** [comment]
my bad I updated it :)

**Comment by fayeed** [comment]
@irfanbacker That seems like a good feature we will definitely include it. @themadmrj The library you shared looks good, I will definitely keep it in mind while working on v2.

**Comment by aytunch** [comment]
I just saw this package, do we have swipe to reply?

https://github.com/Purvik/SwipeTo

**Comment by SebastienBtr** [comment]
@aytunch Yes we could add a swipe for the reply feature.
Dashchat already supports group chats.

**Comment by kherld-hussein** [comment]
> @aytunch Yes we could add a swipe for the reply feature.
> Dashchat already supports group chats.

Kinda like the feature

**Comment by NeoLSN** [comment]
Provide a way to re-use those message builders in customize builder.

**Comment by prufect** [comment]
Maybe add a reacts feature? Like on facebook messager. Long press a the message to show a popup with emojis. Would be great to make it a builder so we can add our own custom emojis

**Comment by giorgio79** [comment]
Please provide Firebase sample integration, with proposed database structure and Firebase cloudstore security rules.
Could be tailored for various scenarios, like 1 to 1 chat, 1 to many, many to many.

Another project is already providing Firebase structure with security rules as well https://pub.dev/packages/flutter_firebase_chat_sdk

**Comment by asantainnasa** [comment]
I love v1! Several features could improve it even further. 
1. Search history search
2. option to automatically linkify text - i currently use linkify along with url_launcher

**Comment by themadmrj** [comment]
what's the ETA on v2?
I will have to start my chat in january at the latest. I'll work on it full time. So either I make my own lib, or the v2 is in progress and I can take over several parts of it.

**Comment by aytunch** [comment]
Will there be a new package for v2 or will it overwrite v1?

**Comment by fayeed** [comment]
@themadmrj I am planning to start this month & @aytunch It will overwrite v1.

**Comment by themadmrj** [comment]
> @themadmrj I am planning to start this month & @aytunch It will overwrite v1.

lmk if you need help for something, can do anything except tests ^^

**Comment by ayushin** [comment]
How about adding support for choosing a conversation/topic/request? 

And perhaps adding backend plugins for tiledesk, chatwoot, chat21 and a few more out of the box or as separate sub packages?

We can contribute.

**Comment by brianjohnson0123** [comment]
I would recommend parameterizing the horizontal padding in the overall message window so that if set to zero, avatars or messages (if no avatars) would sit right up against the edge of the screen (in the example case of DashChat filling the screen)

if I am reading it correctly, it looks like a 2% of the overall width is being applied to the left and to the right padding currently.

**Comment by jinfagang** [comment]
@fayeed  Hi Fay! thanks for your wonderful opensource this widget, it's really helpful! I have serveral questions and suggestions:

- questions:
1. when will v2 have a beta version?
2.  I want using it in a REAL chat app, that will introduce person2person chat, as well as group chat, will it support some group chat messages?

- sugesstions:
1. v1 is enough rich fuctional for me! if you have v2, can we consider add customize emoij support? I mean, it's part of rich text support in messages, jjust like facebook messenger which can enlarge your emojis if it's pure emojis.
2. If inputing animation can be added that would be very nice!

**Comment by themadmrj** [comment]
@fayeed any news? I'd like to start working with it or on it :)

**Comment by diegogarciar** [comment]
Hello, 
As a request, support for audio messages would be nice. @fayeed I'm actually implementing it right now for production, if you want a PR with it in a later beta please let me know.

**Comment by hafidzaini** [comment]
how about reply with quote feature? 🤔

**Comment by themadmrj** [comment]
I've created my own library, since the v2 was aiming to be a global refactor anyways.
More on [https://github.com/themadmrj/chat_ui_kit](https://github.com/themadmrj/chat_ui_kit).
I'll add more features in a bit. PRs are welcome.

**Comment by jinfagang** [comment]
@themadmrj  Looks great ! Let's move on your repo for discussion and contribution, this repo seems not matinained and v2 is just a plan no one work on it.

**Comment by m-j-g** [comment]
> I've created my own library, since the v2 was aiming to be a global refactor anyways.
> More on https://github.com/themadmrj/chat_ui_kit.
> I'll add more features in a bit. PRs are welcome.

@themadmrj I like the initiative!  Are you planning on having test coverage for your kit, like is mentioned as a goal for dash_chat?  With PR's being welcome, I would think it should be mandatory in order to maintain a healthy package?

**Comment by themadmrj** [comment]
@m-j-g that would be the ideal case. However, I have very little experience with tests (being self-taught), so ideally someone would get started on it to show the way!

**Comment by SebastienBtr** [comment]
Thanks everyone for contributing to this discussion, a lot of good ideas!

**Comment by SebastienBtr** [comment]
Thank everyone for contributing to this discussion, a lot of great ideas! I'll close it now as we have far enough ideas/spec, further discussion will be conducted when we launch an MVP. The first version of the v2 will be available in January and then features will be implemented incrementally, with hopefully some good feedback from the community 😀

**Comment by shah-xad** [comment]
It's march, where's the v2??

**Comment by jinfagang** [comment]
@SebastienBtr It's April, where's the v2?

**Comment by denes16** [comment]
Its september, any news?

**Comment by m-j-g** [comment]
For those who end up here looking for an update. This package is no longer being worked on. I switched to flyer chat which has been quite nice:
https://github.com/flyerhq/flutter_chat_ui

**Comment by SebastienBtr** [comment]
I started working on the v2 and pushed it here: https://github.com/molteo-engineering-team/Dash-Chat-2, there is no documentation yet and it's not 100% done but the core features are there. Feel free to take a look/try it. (It's not published yet as it's not done but you can still try it by added the repo link in your dependencies)

I obviously have a lot of other things on the plate but I'm trying to work on it when I have some time, we are still using the v1 in production in my company and it's working fine with all the added logic and overwritten code that we made. 

However, the goal is to make it easier for everyone and not have to implement all this complexity while keeping it highly customizable for people who want to go crazy with  it

**Comment by denes16** [comment]
> I started working on the v2 and pushed it here: https://github.com/molteo-engineering-team/Dash-Chat-2, there is no documentation yet and it's not 100% done but the core features are there. Feel free to take a look/try it. (It's not published yet as it's not done but you can still try it by added the repo link in your dependencies)
> 
> I obviously have a lot of other things on the plate but I'm trying to work on it when I have some time, we are still using the v1 in production in my company and it's working fine with all the added logic and overwritten code that we made.
> 
> However, the goal is to make it easier for everyone and not have to implement all this complexity while keeping it highly customizable for people who want to go crazy with it
On, october, we will start building an app, do you recommend to use the version 1 for prod or the version 2, or flutter_chat_ui? Thx

**Comment by SebastienBtr** [comment]
@denes16 I would recommend using the v2, the v1 is not maintained anymore
