### ISSUE TITLE
Any examples on working outside of firebase? 

### ISSUE THREAD

**Issue by Aynn** [fayeed/dash_chat#129]
I am particularly stuck on figuring out the data structure for messages.

I am thinking the data from the server might look something like this:
` var data = "[ { \"createdAt\": 1, \"user\": { \"name\": \"John Doe\", \"text\": \"Hello there\" } } ]";`

and I am currently parsing it like so:
```
         var messages = json.decode(data).map((i)=>ChatMessage.fromJson(i)).toList();
              messages = new List<ChatMessage>.from(messages);
```
However I can't seem to get it right and don't have access to Firebase to see what their data.snapshot looks like to try to mimic.

Any help would be appreciated!

**Comment by Aynn** [comment]
Ended up just replacing my code with:
```
json.decode(snapshot.data).forEach((i) {
    messages.add(ChatMessage(createdAt: DateTime.parse(i['createdAt']), user: ChatUser(name: i['user']['name']), text: i['user']['text']));
});
```

Working on the onSend method now.

**Comment by fayeed** [comment]
@Aynn `ChatMessage.fromJson` should work as expected, maybe you can check if the parsing works correctly by printing it as a string to console.

**Comment by SebastienBtr** [comment]
You can do whatever structure you want in your database that suits your need/what seems scalable for you, and simply have an adapter in your Flutter app.

**Comment by ryanhz** [comment]
I do make the example work outside of firebase with static data

**Comment by Dreamersoul** [comment]
I have integrated it with a rails backend using action cable, you just need to map the data from your backend to the appropriate class `ChatMessage`

**Comment by SebastienBtr** [comment]
I added in the v2 goals (in #127) to add examples with different databases
