### ISSUE TITLE
ChatMessage not cleared after calling onSend

### ISSUE THREAD

**Issue by emadd** [fayeed/dash_chat#13]
After submitting a new message (onSend), the widget does not reset the state of the send button and will continue to send the last text entered every time it is clicked

**Comment by Lionelvsv** [comment]
you should  overrride the  default text input  and  use  onTextChange to  update  the input

`
void onSend(ChatMessage message) {
    setState(() {
      widget.channel.sink.add(jsonEncoder.convert(msg));
    });
    _msg = '';
  }

 void onTextChange(String text) {
    setState(() {
      this._msg = text;
    });
  }

DashChat(
                text: _msg,
                onTextChange: onTextChange,
);
`

**Comment by fayeed** [comment]
@emadd  Just fixed this you can check the `v1.0.11`, it also includes few more fixes.

**Comment by sijangurung** [comment]
This error still exists with dash_chat: ^1.1.3. I am doing the same logic as mentioned above , and the input textfield is not clearing after send !
DashChat(
...
text: _inputMessage,
                      onTextChange: (txtchange){setState(() => _inputMessage = txtchange)},
...

**Comment by sijangurung** [comment]
Found workaround. While sending from custom method, just call
    _chatViewKey.currentState.textController.clear();
For clearing the input field !
