### ISSUE TITLE
[Bug] App crashes when opening chat in release mode

### ISSUE THREAD

**Issue by Andresdn14** [fayeed/dash_chat#134]
Right now I’m having an issue that for the moment there is no way I could find the possible reason. The thing is that when I’m in debug mode, the chat works perfect, beautiful and swift, but when I upload my app to testflight, the chat crashes almost immediately, sometimes, does not crashes immediately, but the input box disappears, then I touch where the input should be, and then it crashes.

I don’t really know what to do and I’m incredibly desperate because it only crashes release, so there's no way I could know why this is happening by seeing a print or something.

1. Add dash chat to a Flutter app
2. Verify it works on debug mode in the simulator
3. Deploy to Testflight
4. See error when opening the chat

 - OS: [Mas OSX Catalina]
 - Device: working on iPhone 11/ iPhone 11 Pro Max simulator iOS 13(latest) and crashes on iPhone 11 (iOS 13 latest and iOS 14 beta)

The rest of the app works perfect, I made even the release build process and everything.

**Comment by Andresdn14** [comment]
It also works in a physical device when debugging

**Comment by fayeed** [comment]
Have you tried the latest version for the package `1.1.15`

**Comment by Andresdn14** [comment]
Ok I'll try

**Comment by Andresdn14** [comment]
@fayeed It didn't work even when updating the package.
I got to take a Screenshot without touching anything, before the crash.
Sometimes the chat does not crash immediately but this happens:
![image](https://user-images.githubusercontent.com/38304182/92707024-9869ef00-f31a-11ea-92d1-91cac792a197.png)

The input gets transparent, In debug mode the chat works perfect

**Comment by Andresdn14** [comment]
Hello, there's still no clue about what could be the reason for the crash on release?

**Comment by fayeed** [comment]
@Andresdn14 I have never seen this issue before, there are lots of people using this package in production & never heard of this issue before. I was wondering do you see this issue on both Android & IOS or just IOS. Also, it would be great if you can share your code for Dashchat here.

**Comment by Andresdn14** [comment]
Just iOS, I have 2 apps (Doctors and patients), and the chat is crashing in both of them, in the iOS version o testflight.
Here's my code:


`
import 'dart:async';
import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dash_chat/dash_chat.dart';
import 'package:doctor_pro_app/components/appbar.dart';
import 'package:doctor_pro_app/components/loader.dart';
import 'package:doctor_pro_app/constants/constants.dart';
import 'package:doctor_pro_app/locator.dart';
import 'package:doctor_pro_app/models/chat.dart';
import 'package:doctor_pro_app/models/chat_message.dart';
import 'package:doctor_pro_app/models/professional.dart';
import 'package:doctor_pro_app/services/chat_service.dart';
import 'package:doctor_pro_app/services/cloud_storage_service.dart';
import 'package:doctor_pro_app/services/dashboard_service.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:lottie/lottie.dart';
import 'package:platform_action_sheet/platform_action_sheet.dart';

class ChatScreen extends StatefulWidget {
  Professional professional;
  Chat chat;

  ChatScreen({@required this.professional, @required this.chat});

  @override
  _ChatScreenState createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final GlobalKey<DashChatState> _chatViewKey = GlobalKey<DashChatState>();
  final ChatService _chatService = locator<ChatService>();
  final CloudStorageService _cloudStorageService =
      locator<CloudStorageService>();
  UserAndPatient userAndPatient;

  ChatUser user;

  List<ChatMessage> messages = List<ChatMessage>();
  var m = List<ChatMessage>();

  var i = 0;

  @override
  void initState() {
    super.initState();
  }

  void systemMessage() {
    Timer(Duration(milliseconds: 300), () {
      if (i < 6) {
        setState(() {
          messages = [...messages, m[i]];
        });
        i++;
      }
      Timer(Duration(milliseconds: 300), () {
        print(' Este se ejecuto oite');
        _chatViewKey.currentState.scrollController
          ..animateTo(
            _chatViewKey.currentState.scrollController.position.maxScrollExtent,
            curve: Curves.easeOut,
            duration: const Duration(milliseconds: 300),
          );
      });
    });
  }

  CMessage chatMessageToCMessage(ChatMessage chatMessage) {
    var json = {
      'id': chatMessage.id,
      'text': chatMessage.text,
      'image': chatMessage.image,
      'dateTime': chatMessage.createdAt,
      'sender': userAndPatient.patient.selfReference,
      'selfReference': widget.chat.selfReference
          .collection('messages')
          .document(chatMessage.id),
      'read': false,
    };
    return CMessage.fromData(json);
  }

  void notOnSend(ChatMessage message) async {
//    print('Esto se corre oite');
    //print(message.toJson());

    CMessage cMessage = chatMessageToCMessage(message);
    bool sent =
        await _chatService.sendMessage(cMessage, widget.chat.selfReference);

    if (sent) {
      print('Enviado muñeco');
      Timer(Duration(milliseconds: 300), () {
        _chatViewKey.currentState.scrollController
          ..animateTo(
            _chatViewKey.currentState.scrollController.position.maxScrollExtent,
            curve: Curves.easeOut,
            duration: const Duration(milliseconds: 300),
          );
      });
    } else {
      print('Nel muñeco');
    }
  }

  void anotherFunction(File result) async {
    var cloudStorageResult = await _cloudStorageService.uploadChatImage(
        chatImageName: '${userAndPatient.patient.patientID}/',
        imageToUpload: result);
    print(cloudStorageResult.imageUrl);
    ChatMessage message =
        ChatMessage(text: "", user: user, image: cloudStorageResult.imageUrl);
//    print("Message image");
//    print(message.image);
//    print("/Message Image");
    notOnSend(message);
  }

  void onSend(ChatMessage message) async {
    print('Esto se corre oite');
    //print(message.toJson());
    CMessage cMessage = chatMessageToCMessage(message);
    bool sent =
        await _chatService.sendMessage(cMessage, widget.chat.selfReference);

    if (sent) {
      print('Enviado muñeco');
      Timer(Duration(milliseconds: 300), () {
        _chatViewKey.currentState.scrollController
          ..animateTo(
            _chatViewKey.currentState.scrollController.position.maxScrollExtent,
            curve: Curves.easeOut,
            duration: const Duration(milliseconds: 300),
          );
      });
    } else {
      print('Nel muñeco');
    }

    /*var documentReference = Firestore.instance
        .collection('messages')
        .document(DateTime.now().millisecondsSinceEpoch.toString());

    Firestore.instance.runTransaction((transaction) async {
      await transaction.set(
        documentReference,
        message.toJson(),
      );
    });*/

/*
    setState(() {
      messages = [...messages, message];
      print(messages.length);
    });

    if (i == 0) {
      systemMessage();
      Timer(Duration(milliseconds: 600), () {
        systemMessage();
      });
    } else {
      systemMessage();
    }*/
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<UserAndPatient>(
      future: _chatService.getUserAndPatient(), // async work
      builder: (BuildContext context, AsyncSnapshot<UserAndPatient> snapshot) {
        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return Center(child: Loader());
          default:
            if (snapshot.hasError) {
              print(snapshot);
              return Center(child: new Text('Error: ${snapshot.error}'));
            } else {
              userAndPatient = snapshot.data;
//                        print(userAndPatient);
              user = ChatUser(
                name: userAndPatient.user.name,
                uid: userAndPatient.user.id,
                avatar: userAndPatient.patient.pictureURL,
              );
              return _chatWidgetScreen();
            }
        }
      },
    );
    ;
  }

  Widget _chatWidgetScreen() {
    return Scaffold(
      // backgroundColor: kLightGray,
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(100.0),
        child: CustomAppBar(
          text: widget.professional.name,
          textSize: 32,
        ),
      ),
      body: SafeArea(
        child: StreamBuilder(
            stream:
                widget.chat.selfReference.collection('messages').snapshots(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting)
                return Loader();
              if (!snapshot.hasData) {
                return Center(
                  child: Loader(),
                );
              } else {
                List<DocumentSnapshot> items = snapshot.data.documents;
                var preMessages = [];
                var patientUser = {
                  'name': userAndPatient.user.name,
                  'uid': userAndPatient.patient.patientID,
                  'avatar': userAndPatient.patient.pictureURL,
                };
                var professionalUser = {
                  'name': widget.professional.name,
                  'uid': widget.professional.professionalID,
                  'avatar': widget.professional.pictureURL,
                };
                print(items.length);
                for (int i = 0; i < items.length; i++) {
                  var item = items[i];
//                  print(item.data['sender'].path == userAndPatient.patient.selfReference.path);
//                  print("Item data sender path");
//                  print(item.data['sender'].path);
//                  print("-------");
//                  print("user and Patient patient self reference path");
//                  print(userAndPatient.patient.selfReference.path);
                  var itemData = {
                    'id': item.data['id'],
                    'text': item.data['text'],
                    'createdAt': item.data['dateTime'].millisecondsSinceEpoch,
                    'image':
                        (item.data['image'] == '') ? null : item.data['image'],
                    'user': item.data['sender'].path ==
                            userAndPatient.patient.selfReference.path
                        ? patientUser
                        : professionalUser,
                  };

                  preMessages.add(itemData);
                }
                preMessages.sort((a, b) {
                  var adate = a['createdAt']; //before -> var adate = a.expiry;
                  var bdate = b['createdAt']; //before -> var bdate = b.expiry;
                  return adate.compareTo(
                      bdate); //to get the order other way just switch `adate & bdate`
                });
                var messages =
                    preMessages.map((i) => ChatMessage.fromJson(i)).toList();
                _chatService.ghostThatGial(widget.chat.selfReference,
                    userAndPatient.patient.selfReference);
                return DashChat(
                  key: _chatViewKey,
                  inverted: false,
                  onSend: onSend,
                  sendOnEnter: true,
                  textInputAction: TextInputAction.send,
                  user: ChatUser.fromJson(patientUser),
                  inputDecoration: InputDecoration.collapsed(
                      hintText: "Escribe un mensaje.."),
                  dateFormat: DateFormat('yyyy-MMM-dd'),
                  timeFormat: DateFormat('HH:mm'),
                  messages: messages,
                  showUserAvatar: true,
                  showAvatarForEveryMessage: false,
                  scrollToBottom: false,
                  onPressAvatar: (ChatUser user) {
                    print("OnPressAvatar: ${user.name}");
                  },
                  onLongPressAvatar: (ChatUser user) {
                    print("OnLongPressAvatar: ${user.name}");
                  },

                  inputMaxLines: 5,
                  messageContainerPadding:
                      EdgeInsets.only(left: 5.0, right: 5.0),
                  alwaysShowSend: true,
                  inputTextStyle: TextStyle(fontSize: 16.0),
                  inputToolbarMargin: EdgeInsets.all(24),
                  inputContainerStyle: BoxDecoration(
                      border: Border.all(width: 1, color: kLightGray),
                      color: Colors.white,
                      borderRadius: BorderRadius.all(Radius.circular(8))),
                  onLoadEarlier: () {
                    print("Cargando...");
                  },
                  shouldShowLoadEarlier: false,
                  showTraillingBeforeSend: true,
                  trailing: <Widget>[
                    IconButton(
                      icon: Icon(
                        Icons.photo,
                        color: kDarkAquamarine,
                      ),
                      onPressed: () async {
                        File result;
                        PlatformActionSheet().displaySheet(context: context,
//        title: Text('Elegir foto de perfil', style: kTextFieldLabelStyle,),
//        message: Text("Elige cómo quieres darnos tu foto de perfil"),
                            actions: [
                              ActionSheetAction(
                                text: "Galería",
                                onPressed: () async {
                                  result = await ImagePicker.pickImage(
                                    source: ImageSource.gallery,
                                    imageQuality: 80,
                                    maxHeight: 400,
                                    maxWidth: 400,
                                  );
                                  anotherFunction(result);
                                  Navigator.of(context,
                                          rootNavigator: Platform.isIOS)
                                      .pop();
                                },
                              ),
                              ActionSheetAction(
                                text: "Cámara",
                                onPressed: () async {
                                  result = await ImagePicker.pickImage(
                                    source: ImageSource.camera,
                                    imageQuality: 80,
                                    maxHeight: 400,
                                    maxWidth: 400,
                                  );
                                  anotherFunction(result);
                                  print(result);

                                  Navigator.of(context,
                                          rootNavigator: Platform.isIOS)
                                      .pop();
                                },
                              ),
                              ActionSheetAction(
                                text: "Cancelar",
                                onPressed: () {
                                  result = null;
                                  Navigator.of(context,
                                          rootNavigator: Platform.isIOS)
                                      .pop();
                                },
                                isCancel: true,
                                defaultAction: true,
                              )
                            ]);

                        if (result != null) {
                          print('Esto se corre vol 2');
                          /*final StorageReference storageRef = FirebaseStorage
                              .instance
                              .ref()
                              .child("chat_images/" +
                                  '${userAndPatient.patient.id}/' +
                                  DateTime.now()
                                      .millisecondsSinceEpoch
                                      .toString());

                          StorageUploadTask uploadTask = storageRef.putFile(
                            result,
                            StorageMetadata(
                              contentType: 'image/jpg',
                            ),
                          );
                          StorageTaskSnapshot download =
                              await uploadTask.onComplete;

                          String url = await download.ref.getDownloadURL();*/
                          var cloudStorageResult =
                              await _cloudStorageService.uploadChatImage(
                                  chatImageName:
                                      '${userAndPatient.patient.id}/',
                                  imageToUpload: result);
                          ChatMessage message = ChatMessage(
                              text: "",
                              user: user,
                              image: cloudStorageResult.imageUrl);
                          notOnSend(message);
                          /*var documentReference = Firestore.instance
                              .collection('messages')
                              .document(DateTime.now()
                                  .millisecondsSinceEpoch
                                  .toString());

                          Firestore.instance
                              .runTransaction((transaction) async {
                            await transaction.set(
                              documentReference,
                              message.toJson(),
                            );
                          });*/
                        }
                      },
                    )
                  ],
                );
              }
            }),
      ),
    );
  }
}

`

**Comment by Andresdn14** [comment]
Ok, I think the problem was the edited input bar, so I removed every decoration, every difference between the example and the one in my code, and it worked, I don't know why that generated a crash in production.

Again, thanks for this package, I love it.

**Comment by Andresdn14** [comment]
Specifically when adding inputToolbarMargin: `EdgeInsets.all(24)`

**Comment by fayeed** [comment]
That's weird, don't know what's happening will have to take a look. Thanks for narrowing down the issue though @Andresdn14.
