### ISSUE TITLE
[Bug] setState called() after dispose()

### ISSUE THREAD

**Issue by arnelochner** [fayeed/dash_chat#135]
**Describe the bug**
When creating a DashChat Widget and disposing it before the scrollController finished its animation, setState is called after the animation is finished. 
This leads to an unhandled expection.

**To Reproduce**
1. Navigate to a Scafold page, where the DashChat widget is the child (to create a BackButton)
2. Immediately use the Backbutton (before Controller finished its animation)
3. See error

**Expected behavior**
setState() is not called after the widget is disposed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57033688/93714701-d1009880-fb64-11ea-8a01-8237cb96adee.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Device: Emulator
 - Flutter Version: 1.17.3
 - Dart Version: 2.8.4
 - Version 1.1.14

**Solution**

Override setState() method for DashChatState to check if the widget is still mounted:

```
@override
  void setState(void Function() fn) {
    if (this.mounted) {
      super.setState(fn);
    }
  }
```

**Comment by fayeed** [comment]
@arnelochner Have you tried v1.1.15?

**Comment by arnelochner** [comment]
@fayeed Yes! Thanks.
