### ISSUE TITLE
The argument type 'Map<String, dynamic> Function()' can't be assigned to the parameter type 'Map<dynamic, dynamic>'.

### ISSUE THREAD

**Issue by mdridley** [fayeed/dash_chat#155]
**Describe the bug**
Trying to get the example app working. Not sure how to get around this part though.

Getting it on this line for i.data:
var messages = items.map((i) => ChatMessage.fromJson(i.data)).toList();

**Comment by diegogarciar** [comment]
is `I` a snapshot? you might need to do `i.data()` as it is a function that must be called

**Comment by mdridley** [comment]
I am using the code directly from GitHub (and the example tab).

Thanks, that fixed that, but now hitting a bunch of runtime errors.
