### ISSUE TITLE
Static Input Bar

### ISSUE THREAD

**Issue by emmett-deen** [fayeed/dash_chat#16]
**Is your feature request related to a problem? Please describe.**
Right now when using Dash Chat the input bar scrolls away when scrolling through the chat. Most chat systems today have a static chat bar so you can start typing while looking at other chats. I also get frustrated when using the current input bar because it has padding/margin issues when working on iPhone or if I want a bottom navigation bar under the input.

**Describe the solution you'd like**
A static input bar that will lock to the bottom of the screen (also with adjustable padding and margin) or an option to completely hide the built in input bar and hide our own.

**Describe alternatives you've considered**
I have not been able to find a solution directly to the problem regarding having a bottom navigation bar with the chat system. I do understand this is normally not ideal anyway but is necessary for an application I am building.

**Additional context**
I plan on implementing this myself and will submit a pull request. I will try and make this optional so it can be compatible with old projects.

**Comment by yoyoyo11** [comment]
@emmett-deen Were you able to find a solution to make the Input bar static? I could use some guidance on how to fix. Thanks!

**Comment by fayeed** [comment]
@emmett-deen I think this issue is similar to #10 If it is then I have fixed it you can check `v1.0.11`.

**Comment by emmett-deen** [comment]
> @emmett-deen I think this issue is similar to #10 If it is then I have fixed it you can check `v1.0.11`.

I will check it out!

**Comment by SebastienBtr** [comment]
I think this issue can be closed.
