### ISSUE TITLE
[Feature request] Any plans to support null_safety? 

### ISSUE THREAD

**Issue by jonchui** [fayeed/dash_chat#165]
**Is your feature request related to a problem? Please describe.**
We are looking to use DashChat in a sendbird-backe chatting app, and want to migrate to `null-safety`. https://dart.dev/null-safety/migration-guide

But according to the migration guide, ☝️ , it says all our dependencies need to support it first. 

**Describe the solution you'd like**
Migrate DashChat to null-safety using `dart migrate`

**Describe alternatives you've considered**

**Additional context**

**Comment by diegogarciar** [comment]
Hello @jonchui 
I have submitted a pull request, you can use my branch in the meantime at https://github.com/diegogarciar/dash_chat

Please test it and let me know if theres an issue

**Comment by jonchui** [comment]
Amazing!!! 🙏 will test next week when back in office.

FYI @Rachel @Jon

Jon Chui | YwamKona.org ( http://YwamKona.org ) | http://jonchui.com | @jonchui ( http://twitter.com/jonchui )

life verse: Matt 13:44 | our family blog @ vickiandjon.com ( http://vickiandjon.com ) | ping me if you have exciting freelancing projects ;) | 424-241-2484

Sent via Superhuman iOS ( https://sprh.mn/?vip=jon.chui@gmail.com )

**Comment by fayeed** [comment]
@jonchui Package is updated to `1.1.15-nullsafety`, thanks to @diegogarciar.
