### ISSUE TITLE
[Bug] firebase_auth >=1.0.1 is incompatible with dash_chat ^1.1.15

### ISSUE THREAD

**Issue by abegehr** [fayeed/dash_chat#168]
**Describe the bug**
The latest version of dash_chat is incompatible with the latest flutterfire, specifically firebase_auth >=1.0.1

**To Reproduce**
Start a new project and add these dependencies:

```
dash_chat: ^1.1.15
firebase_core: ^1.0.1
firebase_auth: ^1.0.1
```

**Expected behavior**
dash_chat is compatible with the latest and greatest of Flutter 2 and flutterfire.

**Desktop (please complete the following information):**
 - OS: macOS
 - Device: iPhone
 - Flutter Version: 2.0.1
 - Dart Version: sdk: ">=2.7.0 <3.0.0"
 - Version 1.1.15

**Additional context**
The latest [flutterfire](https://github.com/FirebaseExtended/flutterfire) was released recently after Flutter 2.
Is there a nullsafety version of this package we might use with Flutter 2 and the latest of flutterfire?

**Comment by fayeed** [comment]
Use version `1.1.15-nullsafety`
