### ISSUE TITLE
ChatMessage() with onTap

### ISSUE THREAD

**Issue by develbass** [fayeed/dash_chat#18]
ChatMessage() does not have the onTap() event, it is important for a message like localization that needs to open the map.

**Comment by fayeed** [comment]
@develbass I think a better way would be to have a separate property for locations coordinates in `ChatMessage` object and based on this show a Map in the message and an `onTapMap` property to interact with it.

**Comment by SebastienBtr** [comment]
I think it's probably not a good idea to have an onTap property because it will introduce a conflict with flutter_parsed_text.

**Comment by SebastienBtr** [comment]
Closing this issue because there has been no response from the original author. On top of that, it can probably be solved using flutter_parsed_text.
