### ISSUE TITLE
Das chat example app showing progress indicator infinitely

### ISSUE THREAD

**Issue by gopalindians** [fayeed/dash_chat#19]
**Dash chat showing loader infinitely**
I have cloned the example app, when tried to run it is howing infinite loader.

**To Reproduce**
1. Go to '[https://github.com/fayeed/dash_chat/tree/master/example](https://github.com/fayeed/dash_chat/tree/master/example)'
2. clone or copy 'example code'
3. Run flutter using  'flutter run'
4. See 
![photo6102632204283783475](https://user-images.githubusercontent.com/1937433/71949069-258efe00-31f8-11ea-8056-bf7c406eaedf.jpg)

**Expected behavior**
To see the dash chat screen

**Screenshots**
Expected:
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6768426b4235424851676468616d5a3257412f67697068792e676966](https://user-images.githubusercontent.com/1937433/71949131-6129c800-31f8-11ea-97f7-ba3767eac687.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Device: Redmi note 7 pro
 - Flutter Version: 1.12.13+hotfix.5
 - Dart Version: 2.7.0

**Comment by fayeed** [comment]
@gopalindians You will need to add firebase configuration files to the project.
