### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by AshrafLP** [fayeed/dash_chat#21]
when I click on the TextField, an error occurred and can't type within the TextField.

this is the error message :

I/flutter (  568): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (  568): The following assertion was thrown while dispatching notifications for FocusNode:
I/flutter (  568): 'package:flutter/src/services/text_input.dart': Failed assertion: line 401 pos 15:
I/flutter (  568): 'textCapitalization != null': is not true.
I/flutter (  568): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (  568): more information in this error message to help you determine and fix the underlying cause.
I/flutter (  568): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (  568):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (  568): When the exception was thrown, this was the stack:
I/flutter (  568): #2      new TextInputConfiguration (package:flutter/src/services/text_input.dart:401:15)
I/flutter (  568): #3      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1400:9)
I/flutter (  568): #4      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1441:7)
I/flutter (  568): #5      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1707:5)
I/flutter (  568): #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter (  568): #7      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:808:5)
I/flutter (  568): #8      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1401:12)
I/flutter (  568): (elided 12 frames from class _AssertionError and package dart:async)
I/flutter (  568): The FocusNode sending notification was:
I/flutter (  568):   FocusNode#9bed9
I/flutter (  568): ════════════════════════════════════════════════════════════════════════════════════════════════════

am using this version (dash_chat: 1.0.12)

why it's happened?

**Comment by fayeed** [comment]
@AshrafLP I have fixed this check version `1.0.13`
