### ISSUE TITLE
Load Earlier gap customization

### ISSUE THREAD

**Issue by ArneSaknussemm89** [fayeed/dash_chat#22]
**Is your feature request related to a problem? Please describe.**
Currently there is a 100px tall container that causes a wide gap between the start of the messages. Ideally this should be customizable as I want the latest messages to be a little closer to the app bar.

**Describe the solution you'd like**
Ideally a new property called "loadEarlierSpacerHeight" that can be customized with a value.

**Describe alternatives you've considered**
Either forking the project and making the change or trying to use some overly clever Stacks/Transforms.

If this doesn't make sense I can send along a code snippet!

E.g.
<img width="445" alt="Screen Shot 2020-01-25 at 12 13 19 AM" src="https://user-images.githubusercontent.com/16626569/73117250-1b634400-3f08-11ea-96a9-c8baac6910fe.png">

**Comment by fayeed** [comment]
@ArneSaknussemm89 Can you share the code.
