### ISSUE TITLE
Show the username in the message

### ISSUE THREAD

**Issue by LeafarDev** [fayeed/dash_chat#25]
**Is your feature request related to a problem? Please describe.**
It's confusing when there is more than one user without a photo

**Describe the solution you'd like**
Show the username in the message

**Additional context**
Something like discord does:

> Username 27/08/2019
> Message

**Comment by fayeed** [comment]
You can override the `messageBuilder` to implement this feature your self, since this method receive the `ChatMessage` it also contains the user you can use that. It would be simple to implement too.

**Comment by LeafarDev** [comment]
thanks man
