### ISSUE TITLE
Emoji's have a blue tint

### ISSUE THREAD

**Issue by StuartMesham** [fayeed/dash_chat#29]
Emoji's have a blue tint. It is as if they are rendered behind a blue filter. It would be ideal for them to be rendered without this blue colour.

Steps to reproduce:
Create a chat.
Send a message containing an emoji.

Screenshot:
![2020-03-01 13_43](https://user-images.githubusercontent.com/28049022/75625033-c7ace000-5bc2-11ea-85eb-5825bdbf3dae.png)

Tested on LG G5
Android 7.0
dash_chat: ^1.0.15

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 months ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

From the .metadata file:

version:
  revision: 27321ebbad34b0a3fafe99fac037102196d655ff
  channel: stable

project_type: app

**Comment by fayeed** [comment]
@StuartMesham I will look into this.

**Comment by Dreamersoul** [comment]
if you notice you have tint on the text too meaning you just have to set the color for the user like so to make it go away
```dart
    ChatUser(uid: "1", name: "some_user", containerColor: Colors.blue, color: Colors.white)
```
