### ISSUE TITLE
scrollToBottom widget remains visible after leaving chat page

### ISSUE THREAD

**Issue by StuartMesham** [fayeed/dash_chat#30]
I am using package version 1.0.15 and it seems the problem is back. The scrollToBottom widget stays on top of everything even when I leave the chat screen.

This is the same problem that was brought up in issue: https://github.com/fayeed/dash_chat/issues/4

I am using:

dash_chat: ^1.0.15

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 months ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

From the .metadata file:

version:
revision: 27321ebbad34b0a3fafe99fac037102196d655ff
channel: stable

project_type: app

**Comment by fayeed** [comment]
@StuartMesham I don't know, I will check and let you know.

**Comment by MaIronCool** [comment]
Hi. I have a same problem. Package version 1.0.18.
appBar: CupertinoNavigationBar() - when i leaving chat page scrollToBottom widget remains visible.

**Comment by brandonwatkins** [comment]
I am also experiencing the same problem for me using:

dash_chat: ^1.0.18

If the scroll to bottom button is visible and you click the back button in the app bar to pop the screen the button is visible on all screens.

**Comment by SebastienBtr** [comment]
I might take a look at this issue later, it's maybe easy to solve.

To answer to @rlee1990 in #6 :

As a workaround you can use a floating button and add a listener on the scroll controller to show or hide this floating button. And of course when you click on this button you use the scroll controller to scroll down: 

```
final scrollController = _chatViewKey.currentState.scrollController;

// When you click on the button:
scrollController.animateTo(
  scrollController.position.maxScrollExtent,
  curve: Curves.easeOut,
  duration: Duration(milliseconds: 300),
);

// The scroll container listener:
scrollController.addListener(() {
      if (scrollController.offset >= YOUR DESIRED VALUE) {
        // show the floating btn
      } else if (topReached) {
        // hide the floating btn
      }
  });
}
```

I didn't test this code, that's just an idea, hopefully this can help you :)

**Comment by albrownwood** [comment]
same issue seen on 1.1.

**Comment by fayeed** [comment]
@albrownwood @SebastienBtr This has been fixed by the PR from @SebastienBtr, I will release the new version shortly.

**Comment by fayeed** [comment]
Updated the package to `1.1.7`
