### ISSUE TITLE
Private user to user chat with Firebase as backend?

### ISSUE THREAD

**Issue by giorgio79** [fayeed/dash_chat#33]
**Is your feature request related to a problem? Please describe.**
Any plans to make this work with Firebase?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fayeed** [comment]
@giorgio79 If you take a look at the example it uses Firestore as backend, it also contains image upload too. There no plans to integrate Firebase as it is just a UI package but maybe in a future release `v2.0.0`, I might consider this.
