### ISSUE TITLE
Support multiple images

### ISSUE THREAD

**Issue by GroovinChip** [fayeed/dash_chat#38]
Currently, `ChatMessage` only supports one image URL. Please add support for adding more than one image URL.

**Comment by fayeed** [comment]
Right now this is not supported, but I am working on `v2.0.0` which also brings some breaking changes like this one.

**Comment by rlee1990** [comment]
I would love this.

**Comment by elgansayer** [comment]
I achieved this by splitting the media URL and then a custom builder with a  list view.

Though 2.x sounds awesome! Loving this plugin
