### ISSUE TITLE
messageContainerPadding does not work 

### ISSUE THREAD

**Issue by RahulShivkumar** [fayeed/dash_chat#39]
Setting `messageContainerPadding` to any value doesn't seem to work. I think this is because in `message_list_view.dart` I see this (line 39) `this.messageContainerPadding = const EdgeInsets.only(top: 10.0, right: 10.0, left: 10.0),`

I think the padding is always set to this const value vs being set to a value passed in

**Comment by Dreamersoul** [comment]
that line is setting the default value of the padding if it wasn't passed, the value you are passing is being set, try setting it to a high value and see the difference
