### ISSUE TITLE
Consider removing SingleChildScrollView

### ISSUE THREAD

**Issue by Dreamersoul** [fayeed/dash_chat#41]
**Describe the bug**
when `SingleChildScrollView` and the messages less then the viewport, getting the keyboard on and scrolling places the input under the keyboard,
also when it is present and the keyboard is open the user cannot see the last message on top and the view earlier messages widget doesn't shoe

**To Reproduce**
1. Go to 'chat_view'
2. Click on 'textfield'
3. Scroll up to the last message

**Expected behavior**
the last message should appear
**Screenshots**
what happens:
![what happens](https://i.imgur.com/0UstamT.png)
what should happen:
![what should happen](https://i.imgur.com/IH5WEI3.png)
**Desktop (please complete the following information):**
 - OS: Windows
 - Device: Emulator
 - Flutter Version: 1.12.13+hotfix.8
 - Dart Version: 2.7.0
 - Version 1.0.16

**Comment by fayeed** [comment]
Yeah, I have been thinking about removing for a time now, I see that you have created a PR I will take a look and merge it.
