### ISSUE TITLE
Cannot hide avatars

### ISSUE THREAD

**Issue by senordonfelipe** [fayeed/dash_chat#42]
Hey,

I have been working with dash_chat now for a while, however, I am not able to show deactivate the avatars for all users. Right now the avatar is always shown for one user. Although I set `showAvatarForEveryMessage` and `showuseravatar` ar both set to false. It seems that this behavior is not supported at the moment? Can someone confirm this?

**Comment by fayeed** [comment]
@senordonfelipe I am not sure it should work, I will take a look and let you know.

**Comment by shanaya-kanade** [comment]
Hi, I am also setting
 showUserAvatar: false,
                      showAvatarForEveryMessage: false,
but I still see Avatar for one user, what am I missing? I don't want to see any avatar.

Thanks, Shilpi

**Comment by fayeed** [comment]
@shanaya-kanade Just use `avatarBuilder` and return an empty `Container` this should hide the avatar for eveyone.

**Comment by shanaya-kanade** [comment]
Thank you so much @fayeed, that helped !
