### ISSUE TITLE
Hidden input

### ISSUE THREAD

**Issue by JCKodel** [fayeed/dash_chat#43]
**Is your feature request related to a problem? Please describe.**
I want to provide a guided conversation with my user (a help system), using only quick reply buttons.

**Describe the solution you'd like**
A way to completely remove the input box.

**Comment by fayeed** [comment]
This is a really specific use-case and I don't think anyone else would need it, but if enough people request it I will add it.

**Comment by Xheghun** [comment]
input field needs to be hidden when i want to create a custom field

**Comment by jaumard** [comment]
Hum maybe https://github.com/fayeed/dash_chat/pull/66 can be useful for this use case too

**Comment by SebastienBtr** [comment]
You can indeed use the `readOnly` property thanks to @jaumard PR in #66. It will hide the input tool bar.

This issue can be closed.
