### ISSUE TITLE
textDirection

### ISSUE THREAD

**Issue by EngDjango** [fayeed/dash_chat#44]
thanks for the hard work❤
how to change 'textDirection' for the input box?

**Comment by fayeed** [comment]
Right now there is no way to change `textDirection` for `TextField` but it should be a simple fix, I will add this update the package in a couple of hours.

**Comment by fayeed** [comment]
@EngDjango I have added a new property called `inputTextDirection: TextDirection.rtl`.

I have updated the package to `1.0.18`.

**Comment by EngDjango** [comment]
@fayeed ❤thank you fayeed, i really appreciate your fast respond, i wish you best luck;
