### ISSUE TITLE
ChatUser toJson throws invalid Argument error for Color properties

### ISSUE THREAD

**Issue by lazyseals** [fayeed/dash_chat#46]
**Describe the bug**
When saving a chat message into the Firebase database an invalid argument error is thrown: "`Invalid argument: Instance of 'Color'`". This is because the 'containerColor' and 'color' properties of the chat user class are stored directly into the map without conversion to String. 
 
**To Reproduce**
1. Go to the example code of dash chat
2. Extend the ChatUser user with properties for color and containerColor
3. Try to submit a new chatMessage to firebase by invoking the chatMessage.toJson() method
4. See error "`Invalid argument: Instance of 'Color'`"

**Expected behavior**
Please refer to this StackOverflow link in order to see how Colors should normally be treated in a JSON format: https://stackoverflow.com/questions/58812802/how-to-store-and-retrieve-color-from-firestore-in-flutter.

**Comment by fayeed** [comment]
Fixed in v1.0.20

**Comment by fayeed** [comment]
@lazyseals try version 1.1.1

**Comment by SebastienBtr** [comment]
Just tested it, works fine, it can be closed
