### ISSUE TITLE
Add onShow(message) callback for each message shown on chat or a way to determine a Message was shown

### ISSUE THREAD

**Issue by ifanchu** [fayeed/dash_chat#55]
**Is your feature request related to a problem? Please describe.**
I am currently struggling with how to display a Badge on the chat to indicate how many
unread messages are there. I am wondering if it is viable to add a `hasShown` property 
in `ChatMessage` class? Does it make sense? 
Or add a callback `onShow(message)` to `DashChat` so that we can track it ourselves?

**Describe the solution you'd like**
A way to track whether a `ChatMessage` has been shown. 

**Describe alternatives you've considered**
With a callback `onShow(message)` to `DashChat`, we can track it outside of DashChat. 

**Additional context**
Great plugin, really appreciate it.

**Comment by fayeed** [comment]
I think it would be better to have a property called `additionalProperties` or `customProperties` which will be a `Map<string, dynamic>` type so it could suit multiple use cases.

**Comment by fayeed** [comment]
Added a new property in ChatMessage called `customProperties` in v1.0.20.
