### ISSUE TITLE
[feature] add actions to messages

### ISSUE THREAD

**Issue by Dreamersoul** [fayeed/dash_chat#56]
Current I am implementing a chat that requires a button in some chat bubbles for example (open settings) all some other features.

I was thinking of having at the bottom of a message a button bar that renders action if they are present, I can create a PR soon, any suggestion on what should be implemented with it?

**Comment by fayeed** [comment]
I think you could achieve this using `messageBuilder` property.

>`messageBuilder` (Widget Function(ChatMessage)) - Will override the the default message widget.

**Comment by Dreamersoul** [comment]
I am currently using the message builder but in order to have a consistent look I need the `MessageContainer` to have an actions property

**Comment by fayeed** [comment]
Are you thinking of how Slack does it?

**Comment by fayeed** [comment]
As for the API, I think this would be good a new property in `ChatMessage` called `options` or `buttons` would be an array of `MessageOptions`.

```dart
class MessageOptions {
  String title;
  Function onTap;
  BoxDecoration containerStyle;
  TextStyle textStyle;
}
```

**Comment by Dreamersoul** [comment]
Not familiar with slacks API but the `buttons` option seems the way to go for me! I'll work on that today

**Comment by fayeed** [comment]
Updated the package to v1.1.0
