### ISSUE TITLE
Overflow exception 

### ISSUE THREAD

**Issue by jaumard** [fayeed/dash_chat#60]
**Describe the bug**
There is an overflow exception when the chat doesn't take the full width of the screen

**To Reproduce**
Use chat dash in master detail view and send a very long message

**Expected behavior**
Not having overflow 

**Screenshots**
<img width="614" alt="Capture d’écran 2020-04-21 à 10 43 07" src="https://user-images.githubusercontent.com/2970449/79845136-e5c1e000-83bc-11ea-99ab-ac758b0cd061.png">

**Comment by fayeed** [comment]
I think this is because of this: https://github.com/fayeed/dash_chat/blob/d66a7ca35c8253654a654fe8bc8d55e9f68a00a8/lib/src/widgets/message_container.dart#L58

This could easily be resolved by using `LaoutBuilder` in `messageContainer`.

**Comment by jaumard** [comment]
Yes that's why, I'm fixing it right now to remove all MediaQuery usage to use layoutBuilder

**Comment by jaumard** [comment]
I've made the modifications to use layoutBuilder, but it doesn't work as in some case constraints return infinity as height and width. Instead I think we should use FractionallySizedBox to avoir doing the calculation ourselves

**Comment by fayeed** [comment]
I think this might be an issue with wrapping the root widget `DashChat` with `LayoutBuilder` it would be better to wrap `MessageListView`

**Comment by fayeed** [comment]
or maybe try the solution you mentioned.

**Comment by jaumard** [comment]
I have started like this but problem is that other Widget need the constraint (QuickReply, ContainerAvatar...) and I didn't want to wrap all of them with a layoutBuilder to gain in performance as only one is needed. I'll make some try some things....

**Comment by jaumard** [comment]
Ok look like it works with layoutBuilders you can check the PR https://github.com/fayeed/dash_chat/pull/59 here.
