### ISSUE TITLE
message item builders should give the full message object

### ISSUE THREAD

**Issue by jaumard** [fayeed/dash_chat#61]
**Is your feature request related to a problem? Please describe.**
My use case was just to add message status "sent, received, seen" to the message bubble, my idea was to use the `messageTimeBuilder` to add time and message status. Problem is that I don't have the message data on that builder so I can't retrieve my message status. So I had to redo the all message widget with `messageBuilder` instead. Work but much more stuff to take care.

**Describe the solution you'd like**
all message builders should give the full message object instead of just the information that the default widget is showing.

**Comment by fayeed** [comment]
This would help for this use-case and also could be useful but I think this would break the existing code. it could have a second optional parameter for this called `message`.

**Comment by jaumard** [comment]
Sure if we can avoid to have breaking changes it will be better, optional message parameter looks good to me :)
