### ISSUE TITLE
The method '[]' was called on null   ->  Tried calling: []("uid")

### ISSUE THREAD

**Issue by Wizok** [fayeed/dash_chat#63]
**Describe the bug**
Installed the latest version 1.1.0 released today, pasted the example but did not work.

**To Reproduce**
1. Copy the example code
2. Run
3. Error:
_The method '[]' was called on null.
Receiver: null
Tried calling: []("uid")_

**Screenshots**
![image](https://user-images.githubusercontent.com/2520623/80060635-aa2a3180-84f4-11ea-82a3-1b128cc38568.png)

**Additional context**
am i making a mistake or the new version really have an issue ?  first time using this package
- Installed all dependencies
-Tryed with register users on my firebase db.

i could not find the problem =.(

Thanks a lot for your help!

**Comment by fayeed** [comment]
The example code uses Firebase, so you will need to setup Firebase to get it to work.

**Comment by Wizok** [comment]
mmm... im already using firebase, already working with streams in others screens... but this package isn't working for me...

this is the only thing that can be written with the package after it crash

![image](https://user-images.githubusercontent.com/2520623/80063406-76063f00-84fb-11ea-911d-9f968c2e9ece.png)

**Comment by fayeed** [comment]
There is no user object in your Firestone, you also need to add user property with every message.

**Comment by fayeed** [comment]
This how your firestore document should look

![image](https://user-images.githubusercontent.com/8464270/80063680-096b5e80-8554-11ea-997e-b338da21f446.png)

**Comment by fayeed** [comment]
@Wizok I have fixed a small issue with ChatUser class so to try `v1.1.1`

**Comment by Wizok** [comment]
Yooo ! is working, thanks a lot Fayeed =D

![image](https://user-images.githubusercontent.com/2520623/80066643-ee6ffe80-8501-11ea-9cec-45c98be5a74d.png)
