### ISSUE TITLE
Horizontal overflow occurs when message content is too large

### ISSUE THREAD

**Issue by david-shortman** [fayeed/dash_chat#65]
- Message row overflows text reaches a certain length
  - Occurred with avatars visible

[My code using dash_chat](https://github.com/david-shortman/netflix-party-enhancement-suite/blob/master/flutter_app/lib/pages/ChatFeedPage.dart#L91)

![Screen Shot 2020-04-19 at 3 49 00 AM](https://user-images.githubusercontent.com/25187726/79682480-b9596880-81f0-11ea-95cb-0bd79a490dde.png)

**Comment by fayeed** [comment]
@david-shortman This issue was resolved in issue #5. It will take a look and let you know.

**Comment by jaumard** [comment]
Yes should be resolved  if you use last version 1.1.1

**Comment by david-shortman** [comment]
Upgrading the package solved the issue
