### ISSUE TITLE
ScrollController not attached to any scroll views

### ISSUE THREAD

**Issue by lchoua** [fayeed/dash_chat#7]
When we set ScrollController property we have an exception telling us: 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (28833): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (28833): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (28833): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
E/flutter (28833): #3      DashChatState.initState.<anonymous closure> (package:dash_chat/src/chat_view.dart:331:48)
E/flutter (28833): #4      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (28833): #5      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (28833): #6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (28833): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (28833): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (28833): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (28833): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (28833): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (28833): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (28833): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (28833): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
We think that the problem is you use the default scrollController in chat_view.dart (initState) instead of our scrollController.

**Flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale es_AR.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[✓] Connected device (2 available)

**Comment by fayeed** [comment]
Hi @lchoua Thanks for notifying me about this issue, I have taken a look at the problem, I deploy fix it might take me a couple of days though. If you can fix this feel free to create a pull request.

**Comment by fayeed** [comment]
@lchoua Just fixed this issue try version `1.0.9`

**Comment by pricejiang** [comment]
Hi, I am still having this issue only on the Android platform. When I click in the textfield, the keyboard pops up and pops down immediately with this error thrown out.

**Comment by pricejiang** [comment]
> Hi, I am still having this issue. When I click in the textfield, the keyboard pops up and pops down immediately with this error thrown out.

I think managed to solve my problem... The thing is that I wrapped dash_chat under a future builder. When I tap the textfield, it seems that set_state is called and future builder would reload. Then, the scrollcontroller is not attached. The solution is to separate dash chat into another class.

**Comment by LostInDarkMath** [comment]
Hi, I just run into the same problem: I use `DashChat()` inside a `FutureBuilder` and get this error. Can you please explain how I can solve this issue? I don't exactly now what you mean with "separate dash chat into another class". @pricejiang

**Comment by pricejiang** [comment]
> Hi, I just run into the same problem: I use `DashChat()` inside a `FutureBuilder` and get this error. Can you please explain how I can solve this issue? I don't exactly now what you mean with "separate dash chat into another class". @pricejiang

Hi, what I did was wrapped `DashChat` into a separate `StatefulWidget` class so it will keep its own state and will not be refreshed by `FutureBuilder`.

**Comment by LostInDarkMath** [comment]
Thank your very much for your fast answer! I'll try :+1:

**Comment by LostInDarkMath** [comment]
@pricejiang Do you have a hint for me how I can set the state of the `DashChat` wrapper? I don't have any idea how to do this at the moment...

I mean, it has to look something like this:
```python
class Chat extends StatefulWidget {
  final Key _key;
  final Function(ChatMessage) _onSend;
  final Function(ChatUser) _onPressAvatar;
  final Function(ChatUser) _onLongPressAvatar;
  final Function _onLoadEarlier;
  final ChatUser _chatPartner;

  Chat({
    @required Function(ChatMessage) onSend,
    @required Function(ChatUser) onPressAvatar,
    @required Function(ChatUser) onLongPressAvatar,
    @required Function onLoadEarlier,
    @required ChatUser chatPartner,
    Key key,
  })  : assert(onSend != null),
        assert(chatPartner != null),
        assert(onPressAvatar != null),
        assert(onLongPressAvatar != null),
        assert(onLoadEarlier != null),
        _onSend = onSend,
        _chatPartner = chatPartner,
        _onPressAvatar = onPressAvatar,
        _onLongPressAvatar = onLongPressAvatar,
        _onLoadEarlier = onLoadEarlier,
        _key = key,
        super();

  @override
  _ChatState createState() => _ChatState();
}

class _ChatState extends State<Chat> {
  List<ChatMessage> messages = [];

  @override
  Widget build(BuildContext context) {
    return DashChat(
      key: widget._key,
      inverted: false,
      onSend: widget._onSend,
      sendOnEnter: true,
      textInputAction: TextInputAction.send,
      user: widget._chatPartner,
      inputDecoration: InputDecoration.collapsed(
        hintText: 'a hint',
      ),
      messages: messages,
      showUserAvatar: false,
      showAvatarForEveryMessage: false,
      scrollToBottom: true,
      onPressAvatar: widget._onPressAvatar,
      onLongPressAvatar: widget._onLongPressAvatar,
      inputMaxLines: 5,
      messageContainerPadding: EdgeInsets.only(
        left: 5.0,
        right: 5.0,
      ),
      alwaysShowSend: true,
      inputTextStyle: TextStyle(
        fontSize: 16.0,
      ),
      inputContainerStyle: BoxDecoration(
        color: Theme.of(context).backgroundColor,
        border: Border.all(
          width: 0.0,
        ),
      ),
      onQuickReply: (Reply reply) => {print('QuickReply: $reply')},
      onLoadEarlier: widget._onLoadEarlier,
      shouldShowLoadEarlier: false,
      showTraillingBeforeSend: true,
    );
  }
}
```

I'm stuck here.

**Comment by pricejiang** [comment]
Not sure about the context of your implementation, but the state of the `Chat` class should be managed by how your `FutureBuilder` populate data to it.

**Comment by LostInDarkMath** [comment]
Finally, I found a solution for my problem. I decide to don't use `FutureBuilder` at all.
