### ISSUE TITLE
Extedend Chat user

### ISSUE THREAD

**Issue by DeepakPant** [fayeed/dash_chat#70]
Is there any chance we can add additional properties to chat user. Current properties are limited like user type or roles. I want to categorize user based on there role property like support , admin.

**Comment by fayeed** [comment]
@DeepakPant yeah sure we can do that, I will let you know once this is done.

**Comment by fayeed** [comment]
@DeepakPant updated the package to `1.1.4`. Added a new property to the User Model called `customProperties`.
