### ISSUE TITLE
MessageListView aligns itself to bottom. Allow for aligning from Top of View too.

### ISSUE THREAD

**Issue by ngoctranfire** [fayeed/dash_chat#79]
I'm running into an issue where I create a DashChat and it is a full screen chat, but when there is only 1 message currently visible, the messages always position themselves at the bottom. I would like to position the messages starting from the top down instead of from the bottom up as it is currently doing.

**Describe the solution you'd like**
Add a flag into DashChat where we can align messages so that it starts displaying from the Top.
This is only a problem when you say, have only 1 message. You only have 1 message and when you open the view, it is at the bottom.

**Additional context**
The reason I wanted to achieve this is because I want to be able to stack Two bottom tier icons at the bottom and interact with them without overlaying the chat messages. 

Here's what a screenshot of this looks like

![Screen Shot 2020-05-12 at 4 43 19 AM](https://user-images.githubusercontent.com/3119704/81683770-41571a80-940b-11ea-8c37-8292bbcaa221.png)

**Comment by ngoctranfire** [comment]
I have a fix for this and I can make a pull request for this. I decided to add a bool flag to allow the user to set this.

**Comment by fayeed** [comment]
@ngoctranfire Updated the package to v1.1.5
