### ISSUE TITLE
Add the ability to build messageContainerDecoration

### ISSUE THREAD

**Issue by Dreamersoul** [fayeed/dash_chat#85]
**Describe the solution you'd like**
having a `messageContainerDecorationBuilder` will allow different bubbles to have different styles i think this can be helpful to get a better looking chat
for example the current user can have different radius from the user he is chatting with.

**Comment by SebastienBtr** [comment]
Agree with that, in my app as a workaround I did it in the message text builder and used transparent color & 0 padding for the message container

**Comment by Dreamersoul** [comment]
I'm thinking of adding a PR after the one I have gets merged

**Comment by albydarned** [comment]
I would love to be able to keep all the default functionality of each message, but just change the background color. Some messages green, some red, some blue etc.

If someone could point me in the right direction I could attempt a PR.

**Comment by Dreamersoul** [comment]
The code is pretty much self explanatory! You can start with message_container.dart line 91, this is the needed line to be changed

**Comment by fayeed** [comment]
@albydarned `ChatUser` class has a property called `containerColor` which you can use to change the message box color for different users.

**Comment by fayeed** [comment]
If you are looking to do like random message background color you could just use `messageBuilder` to randomly set the background color.

**Comment by albydarned** [comment]
@fayeed Thanks... That might work for what I need. Is there a good way in messageBuilder to use the default message and only change the background color without having to rebuild the whole message component?

**Comment by fayeed** [comment]
@albydarned  `ChatUser` class has a property called `containerColor` which you can set to change chat message background color.

**Comment by albydarned** [comment]
Although this has been closed, what @fayeed suggested also worked great for me. Just had to have some conditional code when I created my `List<ChatMessage>` to use different users with different `containerColor` attributes.
