### ISSUE TITLE
Avatar showing for every message 

### ISSUE THREAD

**Issue by Bobby9292** [fayeed/dash_chat#87]
The avatar 'Initial'  for other users, is still shown after setting both : 
- showUserAvatar
- showAvatarForEveryMessage
to False. 

![image](https://user-images.githubusercontent.com/65888791/82789216-e90d2780-9ea4-11ea-9ad9-42051690b284.png)

**Desktop:**
 - OS: MacOS Catalina 10.15.4
 - Device: Emulator Iphone11 pro Max and physical Android 10 
 - Flutter Version:  1.17.1 
 - Dart Version: 2.8.2

**Comment by SebastienBtr** [comment]
There is no parameter to hide all avatars, but you can use an empty Container in the avatarBuilder, see https://github.com/fayeed/dash_chat/pull/74.

**Comment by Bobby9292** [comment]
Thanks for the reply. 
Worked fined with that workaround.
