### ISSUE TITLE
Other user Avatar grows as window is sized

### ISSUE THREAD

**Issue by boosey** [fayeed/dash_chat#88]
The avatar for the other user grows proportionally to the window (or chat view) width. This is not desired. I know this happens for an avatar which is just and initial. I believe the desired behavior would be the size of the avatar is constant and a bit larger than a single line chat bubble.

To get around this, I had to create an avatar builder and put in constant box contstraints of 500 and 500. This was trial and error. I have no idea what the units are. I have only tested this on a web app.

<img width="194" alt="Screen Shot 2020-06-03 at 10 25 43 AM" src="https://user-images.githubusercontent.com/2569582/83656099-bfc75800-a584-11ea-979d-096629cecdf7.png">

<img width="306" alt="Screen Shot 2020-06-03 at 10 27 27 AM" src="https://user-images.githubusercontent.com/2569582/83656191-db326300-a584-11ea-8c1a-1ccbb0728c07.png">

**Comment by fayeed** [comment]
The reason for this is that we calculate the avatar container height width based on the parent component height, width i.e `width * 0.08`. Since the package is not optimized for the web yet for wider screens can cause this problem.

**Comment by SebastienBtr** [comment]
Should the avatar just use a fixed size?

**Comment by fayeed** [comment]
Maybe adding a constraint to `Container` would be good.

Like this: `constraints: BoxConstraints(minWidth: 40, maxWidth: 40)`

**Comment by fayeed** [comment]
@boosey Added a new property called `avatarMaxSize` defaults to `30.0`. Check the new version 1.1.6
