### ISSUE TITLE
Input footer hidden on keyboard  popup

### ISSUE THREAD

**Issue by Lionelvsv** [fayeed/dash_chat#9]
the widget  inside the input  footer are hidden  when  virtual keyboard is active
![Screenshot 2019-11-28 at 3 26 51 PM](https://user-images.githubusercontent.com/10217987/69796170-8d165e80-11f3-11ea-8942-3fab612ef3d3.png)
![Screenshot_1574514861](https://user-images.githubusercontent.com/10217987/69796171-8d165e80-11f3-11ea-810e-2ae553ad4e29.png)

  inputFooterBuilder: () {
return Column(
                      children: <Widget>[
                        Text('asd'),
                        Text('asd'),
                        Text('asd'),
                        Text('asd'),
                        Text('asd'),
                        Text('asd'),
                      ],
                    );
}

**Comment by scortumee** [comment]
Same here. Were you able to fix it @Lionelvsv?
I am using `dash_chat: ^1.1.3`. @fayeed could you take a look at it? We really appreciate that

**Comment by fayeed** [comment]
@scortumee This has been fixed, Please check version `1.1.8`

**Comment by scortumee** [comment]
thanks @fayeed, will check it out
