### ISSUE TITLE
Add "firstName" and "lastName" on ChatUser

### ISSUE THREAD

**Issue by SebastienBtr** [fayeed/dash_chat#90]
**Describe the solution you'd like**
I'd like to have `firstName` & `lastName` fields on a ChatUser, currently we just have `name`.

**Additional context**
I'm using the `avatarBuilder` to use my own avatar which use the user initials when there is no profile picture. Currently I can't use it properly because we only have access to `name`.

**Comment by fayeed** [comment]
I initially had this but dropped in favour of how google handles first & last name they just separate the name with spaces, but this is doable.

We could allow users to set either first & last name or name, if first & last is present just concat & use it or else use the name field.

**Comment by fayeed** [comment]
@SebastienBtr updated the package to v1.1.6 with these new properties in User Class
