### ISSUE TITLE
name sent is "null null" even though a name is provided in the user object.

### ISSUE THREAD

**Issue by m-j-g** [fayeed/dash_chat#91]
1.) Create a ChatUser object with any 'name'. 
2.) The created object gives back "Null Null" 
(it tries to use first and last name but not sure why, when you supply a name)

I had version set to 'any' - changing it to 1.1.5 resolves the issue.

**Comment by fayeed** [comment]
@m-j-g Thanks for reporting the issue I will take a look

**Comment by lucaspal** [comment]
I opened a PR that fixes this [link to PR](https://github.com/fayeed/dash_chat/pull/92).
@fayeed Have a look when you have time.

**Comment by fayeed** [comment]
@lucaspal  Just merged the PR will release a new version in few minutes

**Comment by lucaspal** [comment]
Great :)

**Comment by fayeed** [comment]
Package updated to `1.1.9`, it should be up in couple of minutes
