### ISSUE TITLE
Calling of 'setState' without if(mounted)

### ISSUE THREAD

**Issue by mateus96mt** [fayeed/dash_chat#95]
**Describe the bug**
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): DashChatState#a79cd(lifecycle state: defunct, not mounted)
E/flutter ( 6239): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 6239): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 6239): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 6239): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
E/flutter ( 6239): #1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
E/flutter ( 6239): #2      DashChatState.widgetBuilt.<anonymous closure>.<anonymous closure> (package:dash_chat/src/chat_view.dart:403:17)
E/flutter ( 6239): #3      _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 6239): #4      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6239): #5      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6239): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 6239): #7      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 6239): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6239): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 6239): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 6239): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 6239): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 6239): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**To Reproduce**
Using the lib sometimes the error appears.

**Expected behavior**
This error should not happen, i guess that adding and 'if(mounted)' before calling 'setState()' would solve.

**Screenshots**
![image](https://user-images.githubusercontent.com/22008143/84681850-234d7000-af0b-11ea-9866-de4ce41771d1.png)

**Desktop (please complete the following information):**
 - OS: Ubunt 20.04
 - Device: Emulator
 - Flutter Version: 1.17.2
 - Dart Version: 2.8.4
 - Version ^1.1.8

**Comment by SebastienBtr** [comment]
Seems duplicated of #93
