### ISSUE TITLE
Swear words filter

### ISSUE THREAD

**Issue by giorgio79** [fayeed/dash_chat#97]
Wondered if swear words filtering would be a good idea? Anyone had issues with user cussing? Perhaps a report button on the interface?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fayeed** [comment]
This is a very specific use case so it won't be implemented, but you can easily achieve what you want by using `messageBuilder` property. You could have a a map or an array of swear words and can check to see if the current message has any swear words. As for report button you can also implement it yourself using the buildin properties.

I am going close this issue.
