### ISSUE TITLE
The following NoSuchMethodError was thrown building LayoutBuilder

### ISSUE THREAD

**Issue by ravivlb** [fayeed/dash_chat#98]
**Describe the bug**
Getting error on the user B side when the message sent from user A.

**To Reproduce**
1. Open both applications at the same time
2. Send message from user A (left side - iOS) 
3. Getting error  on user B (right side - Android)

I/flutter (20091): The following NoSuchMethodError was thrown building LayoutBuilder:
I/flutter (20091): The getter 'values' was called on null.
I/flutter (20091): Receiver: null
I/flutter (20091): Tried calling: values
I/flutter (20091):
I/flutter (20091): The relevant error-causing widget was:
I/flutter (20091):   LayoutBuilder
I/flutter (20091):   
package:dash_chat/src/chat_view.dart:445
I/flutter (20091):
I/flutter (20091): When the exception was thrown, this was the stack:

**Expected behavior**
"Hi" message should be visible on user B side (right side - Android)
**Screenshots**
<img width="853" alt="Screenshot 2020-06-26 at 10 06 40 AM" src="https://user-images.githubusercontent.com/3625118/85821343-13008500-b796-11ea-9f8f-6ce34927b78f.png">

**Desktop (please complete the following information):**
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

**Additional context**

**Comment by kanal-altyapi** [comment]
Same for me, there is an error. If first comment user is own no error otherwise I'm getting an error

**Comment by ChrisChV** [comment]
That error happens to me when I use the version 1.1.10, but with the versión 1.1.9 it works fine for me

**Comment by israbr** [comment]
Hi
Same here, we're in 1.1.9 and we see the red screen of death on Android.
Our wild guess is it might be related to QuickReplies as we do not use this feature.
Fantastic job regardless of this issue ^_^

**Comment by israbr** [comment]
Unlike the op, we are not seeing ANY errors if we use an emulator though

**Comment by israbr** [comment]
We've managed to reproduce in emulator using 1.1.10 and not passing anything for QuickReplies.
We "solve it" by passing:
```
quickReplies: QuickReplies() 
```
to the ChatMessge constructor

**Comment by brad555** [comment]
It appears as if you need to set the quickReplies to be QuickReplies() in a chat message, but you also need to make sure you implement the onLoadEarlier callback in DashChat to get rid of the errors. Just set onLoadEarlier: (){print("loading")}

**Comment by fayeed** [comment]
Just fixed the bug and updated the package to `1.1.11` it should be live in a couple of minutes
